name: 'Release'

on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0

      - uses: 'actions/setup-go@v3'
        with:
          go-version: '1.18'

      - id: import_gpg
        uses: 'crazy-max/ghaction-import-gpg@v5.2.0'
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          passphrase: '${{ secrets.GPG_PASSPHRASE }}'

      - uses: 'goreleaser/goreleaser-action@v3'
        with:
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GPG_FINGERPRINT: '${{ steps.import_gpg.outputs.fingerprint }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
